//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_SMS_DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventId { get; set; }
        public string EventName { get; set; }
        public int MinEffect { get; set; }
        public int MaxEffect { get; set; }
        public bool IsSector { get; set; }
        public bool IsStock { get; set; }
        public int MinDuration { get; set; }
        public int MaxDuration { get; set; }
        public double Probability { get; set; }
        public int Chance { get; set; }
    }
}
