//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_SMS_DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int GameId { get; set; }
        public string GameCode { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string CreatedPlayer { get; set; }
        public int PlayersCount { get; set; }
        public bool IsPublic { get; set; }
        public bool IsActive { get; set; }
        public bool IsStarted { get; set; }
        public bool IsCanceled { get; set; }
    }
}
