//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_SMS_DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerStock
    {
        public int PlayerStockId { get; set; }
        public int StockId { get; set; }
        public int TransactionId { get; set; }
        public int PlayerId { get; set; }
        public int Quantity { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Stock Stock { get; set; }
        public virtual Transcation Transcation { get; set; }
    }
}
