//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_SMS_DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transcation
    {
        public int TransactionId { get; set; }
        public int AccountId { get; set; }
        public bool IsWithdraw { get; set; }
        public bool IsDeposit { get; set; }
        public string Sender { get; set; }
        public string Receiver { get; set; }
        public decimal Amount { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
    }
}
