//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_SMS_DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trend
    {
        public int TrendId { get; set; }
        public string TrendName { get; set; }
        public int MaxEffect { get; set; }
        public int MinEffect { get; set; }
    }
}
