//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_SMS_DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPlayerPortfolio
    {
        public string StockName { get; set; }
        public Nullable<decimal> StartingPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> PlayerId { get; set; }
        public string PlayerName { get; set; }
        public Nullable<int> StockId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> GameId { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public bool IsWithdraw { get; set; }
        public bool IsDeposit { get; set; }
        public decimal Amount { get; set; }
    }
}
